### ISSUE TITLE
No sensors and 'Config flow could not be loaded: undefined'

### ISSUE THREAD

**Issue by ralphhughes** [thecode/ha-onewire-sysbus#36]
Hi,

I upgraded my home assistant and my 4 one-wire temperature sensors stopped working. After researching, I believe the workaround is to install this code, so I have installed this via HACS following the instructions. When I SSH into my host I have the HACS custom_components folder and it contains the onewire_sysbus folder with python files, so looks like the code is installed ok.

After restarting HA a few times I don't see any entities though, despite being able to read my temp sensors fine from /sys/bus/w1/devices via the command line?

I tried going to Settings->Integrations->Add Integration->1-Wire SysBus but when I click that I get the error "Config flow could not be loaded: undefined" after about 30s. There are no entries in home-assistant.log related to this integration that I can find. How do I troubleshoot further please?

**Comment by Napoleon-BlownApart** [comment]
I just experienced the same issue, and whilst I haven't got everything working again yet, I have made some progress.

There have been some MAJOR changes to HA since last year, therefore:

1) Uninstall HACS that you currently have.
2) Remove the 1-Wire Integration you have, that WORKED in the past
3) Reinstall HACS using the instructions at https://hacs.xyz/docs/setup/prerequisites
3a) Update any other integrations/add-ons you have that came via the old HACS (e.g. Node-RED, ...)
       Make sure you restart HA
4) Install the `1-Wire SysBus` integration.

That's where I'm up to.
In the CLI, I can view my thermometers and their temperatures, but the `/sys/bus/w1/devices/
1-Wire SysBus` integration has NO entities and no way to add entities.
I'm in the HACS Discord server asking about this right now.  (*I will update this comment when I figure it out.*)
